// import { useState } from 'react';
// import { useDispatch, useSelector } from 'react-redux';

import Head from 'next/head';

import styles from '@/styles/Home.module.css';

// import { decrement, increment, incrementByAmount, selectCount } from '../redusers/counterSlice';

export default function Home() {
  // const count = useSelector(selectCount);
  // const dispatch = useDispatch();
  // const [incrementAmount, setIncrementAmount] = useState('2');

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>Template</main>
    </>
  );
}
